### ISSUE TITLE
Migrate Homepage to NextJS

### ISSUE THREAD

**Issue by CatherineKiiru** [distributeaid/next-website#136]
## Description
The current website needs to be migrated to NextJS which means you will maintain the design as it is. Refer to this repo to get  the specs. Note, you'll only use NextJS & Tailwind as we figure out how to use Puck on the new website

## Tasks
- [ ] Migrate the current homepage to NextJS. 
- [ ] Implement a data counter with the latest data on DistributeAid's milestones

### Scope

- [ ] Content / Translation
- [X] Design / Frontend (pages & components)
- [ ] Admin / Editor (admin-only functionality, content input, etc)
- [ ] Project (github, production infra, processes, etc)

### Inspiration

Migrating the current website to NextJS

### Relation to DA

- [ ] User - I use DA's projects in my own learning, research, or work.
- [X] Contributor - I volunteer with DA or contribute to it's projects.
- [ ] Beneficiary - I recieve aid that was delivered to frontline distribution groups by DA.
- [ ] Aid Group - I volunteer with a community group that uses DA to send or receive aid.
- [ ] Partner - I work at a DA partner, service provider, or in-kind aid donor.
- [ ] Donor - I donate to DA, or my company sponsors them.
- [ ] Other - None of these options describe my relation to DA.
- [ ] None - This is my first time engaging with DA.

### Followup

- [X] Contribute content or code to help resolve this issue.
- [ ] Review & test the changes to help decide if the issue is resolved.
- [ ] Donate to help DA resolve this issue and maintain this project.
- [ ] Receive a notification when this issue is resolved and the changes are live.
- [ ] Continue to make other contributions to DA's projects, or join DA as a committed volunteer.
- [ ] Recieve more information about DA and this project.
- [ ] After submitting this issue, I do not wish to engage with DA further or recieve any additional followup.

### IP Ownership

Others created the materials, and DA can purchase a private license to use them.

### Attestations & Copyright Assignment

- [X] To assign Distribute Aid the copyright of any materials you created specifically for this project.
- [X] That Distribute Aid has the rights to use any materials you submit which were created by you or others for general use.
- [X] That you have specified any additional licensing requirements related to the materials (crediting the original creators, licensing fees, etc).
- [X] That the materials are not also encumbered by a patent or other types of intellectual property that limit our ability to use them.

### Code of Conduct

- [X] I agree to follow Distribute Aid's Code of Conduct.
